_wandb:
    value:
        cli_version: 0.23.0
        e:
            f6yc397tg1b5qjbsish7pg77ypa1jo07:
                args:
                    - --wandb_name
                    - hori-verti_augment
                codePath: binary_main.py
                codePathLocal: binary_main.py
                email: progaress21@gmail.com
                executable: /usr/bin/python
                host: d1006eee6566
                os: Linux-6.8.0-86-generic-x86_64-with-glibc2.35
                program: /home/cygnus/fujimoto/Cygnus-X_Molecular_Cloud_Analysis/Binary_classification/training/binary_main.py
                python: CPython 3.10.12
                root: /home/cygnus/fujimoto/Cygnus-X_Molecular_Cloud_Analysis/Binary_classification/training
                startedAt: "2025-12-16T06:13:55.838846Z"
                writerId: f6yc397tg1b5qjbsish7pg77ypa1jo07
        m: []
        python_version: 3.10.12
        t:
            "1":
                - 1
                - 5
                - 41
                - 53
            "2":
                - 1
                - 5
                - 41
                - 53
            "3":
                - 1
                - 13
                - 16
            "4": 3.10.12
            "5": 0.23.0
            "12": 0.23.0
            "13": linux-x86_64
fits_random_state:
    value: 123
latent_num:
    value: 100
learning_rate:
    value: 0.0001
train_mini_batch:
    value: 16
val_mini_batch:
    value: 16
weight_decay:
    value: 0.001
