_wandb:
    value:
        cli_version: 0.22.2
        e:
            d5fdwpwe9nwrgue7r91j8t98sro5o6dn:
                args:
                    - --wandb_name
                    - only_128pix
                codePath: train_main.py
                codePathLocal: train_main.py
                cpu_count: 16
                cpu_count_logical: 32
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "1967315451904"
                        used: "477458681856"
                email: progaress21@gmail.com
                executable: /usr/bin/python
                gpu: NVIDIA GeForce RTX 5080
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Blackwell
                      cudaCores: 10752
                      memoryTotal: "17094934528"
                      name: NVIDIA GeForce RTX 5080
                      uuid: GPU-a182a10c-31f9-c38b-ed1f-3f9ffcb84a0a
                host: 88015c1e07b6
                memory:
                    total: "134681849856"
                os: Linux-6.8.0-86-generic-x86_64-with-glibc2.35
                program: /home/cygnus/fujimoto/Cygnus-X_CAE/Cygnus-X_cloud/train_main.py
                python: CPython 3.10.12
                root: /home/cygnus/fujimoto/Cygnus-X_CAE/Cygnus-X_cloud
                startedAt: "2025-11-04T02:09:42.945702Z"
                writerId: d5fdwpwe9nwrgue7r91j8t98sro5o6dn
        m: []
        python_version: 3.10.12
        t:
            "1":
                - 1
                - 5
                - 41
                - 53
            "2":
                - 1
                - 5
                - 41
                - 53
            "3":
                - 1
                - 13
                - 16
            "4": 3.10.12
            "5": 0.22.2
            "12": 0.22.2
            "13": linux-x86_64
fits_random_state:
    value: 123
latent_num:
    value: 100
learning_rate:
    value: 0.0001
train_mini_batch:
    value: 16
val_mini_batch:
    value: 16
weight_decay:
    value: 0.001
