_wandb:
    value:
        cli_version: 0.22.2
        e:
            n6flcvppjg653c4pxa4x9bot4vqcsy2t:
                args:
                    - --wandb_name
                    - only_128pix
                codePath: train_main.py
                codePathLocal: train_main.py
                email: progaress21@gmail.com
                executable: /usr/bin/python
                host: 88015c1e07b6
                os: Linux-6.8.0-86-generic-x86_64-with-glibc2.35
                program: /home/cygnus/fujimoto/Cygnus-X_CAE/Cygnus-X_cloud/train_main.py
                python: CPython 3.10.12
                root: /home/cygnus/fujimoto/Cygnus-X_CAE/Cygnus-X_cloud
                startedAt: "2025-11-04T02:06:31.177861Z"
                writerId: n6flcvppjg653c4pxa4x9bot4vqcsy2t
        m: []
        python_version: 3.10.12
        t:
            "1":
                - 1
                - 5
                - 41
                - 53
            "2":
                - 1
                - 5
                - 41
                - 53
            "3":
                - 13
                - 16
            "4": 3.10.12
            "5": 0.22.2
            "12": 0.22.2
            "13": linux-x86_64
fits_random_state:
    value: 123
latent_num:
    value: 100
learning_rate:
    value: 0.0001
train_mini_batch:
    value: 16
val_mini_batch:
    value: 16
weight_decay:
    value: 0.001
